# Snakefile for the PhageScope data download and processing pipeline
# This Snakefile orchestrates the downloading, merging, and reporting of various phage-related metadata
# and protein fasta files from PhageScope (for now). 
# Each merging is unique and is handled by a dedicated script.


configfile: "config/config.yaml"

import os


# List here the features for which reports will be generated.
# These features correspond to the keys in the config file that contain URLs for metadata.
# Note: the name are directly used, so they must match the keys names (read the rule download_all_tsvs)
# Note: The URL returning errors have been commented out in the config file. 

FEATURES = [
    "phage_metadata", 
    "annotated_proteins_metadata", 
    "transcription_terminator_metadata",
    "phage_trna_tmrna_metadata", 
    "phage_anti_crispr_metadata", 
    "phage_virulent_factor_metadata", 
    "phage_transmembrane_protein_metadata",
    "antimicrobial_resistance_gene_metadata",
    "crispr_array_metadata"
]

# For the fasta files, the snakemake rules simply check that the directories are created but cannot check 
# the content of the directories, as files are too numerous and not named in a predictable way.


# Génération de la liste des dossiers extraits attendus pour les fichiers fasta (protéines)
extracted_dirs_prot = [
    os.path.join(config["protein_fasta_merged_output"], name)
    for name in config["protein_fasta_urls"].keys()
]


# Génération de la liste des dossiers extraits attendus pour les fichiers fasta de phages
extracted_dirs_phages = [
    os.path.join(config["phage_fasta_merged_output"], name)
    for name in config["phage_fasta_urls"].keys()
]


# ----------------------------------------
# RULE ALL (tous les rapports)
# Demander de générer les csv merged est redondant
# ----------------------------------------

rule all:
    input:
        # Generated metadata reports -> triggering the downloading and merging of metadata tsvs
        expand(
            config["reports_output"] + "{feature}_report.html",
            feature=FEATURES
        ),
        # Merging the protein fasta files -> triggering the downloading of protein fasta files
        expand(
            config["protein_fasta_merged_output"] + "{dataset}.fasta",
            dataset=list(config["protein_fasta_urls"].keys())
        ),
        # Merging the phage fasta files -> triggering the downloading of phage fasta files
        expand(config["phage_fasta_merged_output"] + "{dataset}.fasta",
            dataset=list(config["phage_fasta_urls"].keys())
        ),
        # DuckDB database and validation report
        config["optimized_duckdb_output"],
        config["database_validation_report_output"],
        # Sequence indexing files
        config["all_phages_fasta"] + ".fai",
        config["all_proteins_fasta"] + ".fai"


# if launched with auto discovery of snakefile (from the root directory),no need to specify the workflow directory
# Since rules have been moved to a subdirectory, we needed to add "../"to all the paths  
include: "rules/phagescope.smk"

include: "rules/database.smk"

include: "rules/sequences.smk"