site_name: PBI documentation
site_description: Documentation for the PBI repository
# Important: set the full site_url for correct absolute links when hosted under /PBI/
site_url: https://ThibaultSchowing.github.io/PBI/
repo_name: ThibaultSchowing/PBI
repo_url: https://github.com/ThibaultSchowing/PBI
theme:
  name: material
nav:
  - Home: index.md
  - Getting started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
  - User Guide:
      - Data Preparation: user-guide/data-preparation.md
      - Running PBI: user-guide/running-pbi.md
      - Analyzing Results: user-guide/analyzing-results.md
  - Developer Guide:
      - Code Structure: developer-guide/code-structure.md
#      - Contributing: developer-guide/contributing.md
  - API Reference: api-reference.md
  - Changelog: changelog.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ThibaultSchowing/PBI